name: speed_limit_setting
channels:
  - conda-forge
dependencies:
  - pyproj<3
  - shapely
  - black
  - flake8
  - jupyterlab
  - numpy<1.22
  - pip
  - python-dotenv
  - pip:
      - git+https://github.com/dvrpc/plan-belt
      - --editable .
